# Site settings
title: Mirandachen1992
email: 15251857675@163.com
description: 陈泳瑾的博客
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/myBlog" # the subpath of your site, e.g. /blog/
url: "https://mirandachen1992.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mirandachen1992
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
